id = "thrift-next"
name = "Thrift Next"
version = "0.0.1"
schema_version = 1
authors = ["HusuSama <hususama@foxmail.com"]
description = "Thrift Next"
repository = "https://github.com/HusuSama/zed-thrift-next"

[grammars.thrift]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-thrift"
rev = "68fd0d80943a828d9e6f49c58a74be1e9ca142cf"

[language_servers.thriftls]
name = "Thrift Language Server"
languages = ["Thrift"]
